services:
  cpp-server:
    build:
      context: ./cpp-server
      dockerfile: Dockerfile.server_cpp
    container_name: cpp-server
    command: ["./drive-server", "8080"]
    volumes:
      - cpp_storage:/storage_file
    ports:
      - "8080:8080"   
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  nodejs-server:
    build:
      context: ./NodeJS-server
      dockerfile: Dockerfile.NodeJS_server
    container_name: nodejs-server
    depends_on:
      - cpp-server
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - ./NodeJS-server/.env
    environment:
      SERVER_HOST: cpp-server
      SERVER_PORT: 8080
      MONGO_URI: mongodb://mongo:27017/drive
    restart: unless-stopped

volumes:
  cpp_storage:
  mongo_data:
