// nodeJS-server/src/controllers/filesController.js

const filesService = require('../services/filesService');
const permissionStore = require('../services/permissionStore');
const { attachOwnerInfo } = require('../services/ownerInfoService');

// validate file id format (generated by idFileService: f_<digits>_<digits>)
function isValidFileId(id) {
  return typeof id === 'string' && /^f_\d+_\d+$/.test(id);
}

// GET /api/files
// Authentication is enforced by middleware (authService)
// Optional query: ?starred=true
const getFilesInRootForUser = (req, res) => {
  const userId = req.userId;
  const { starred } = req.query || {};

  // Dedicated starred view: include owned + shared, any depth
  if (starred === 'true') {
    const files = filesService.getStarredForUser(userId);
    return res.status(200).json(attachOwnerInfo(files, userId));
  }

  let files = filesService.getFilesInRootForUser(userId);
  return res.status(200).json(attachOwnerInfo(files, userId));
};

// GET /api/files/shared
const getSharedWithMe = (req, res) => {
  const userId = req.userId;
  const files = filesService.getSharedWithUser(userId);
  return res.status(200).json(attachOwnerInfo(files, userId));
};

// GET /api/files/recent
const getRecentFiles = (req, res) => {
  const userId = req.userId;
  const files = filesService.getRecentFiles(userId);
  return res.status(200).json(attachOwnerInfo(files, userId));
};

// GET /api/folders
// Query: ?parentId=<id | null>
const getMoveFolders = (req, res) => {
  const userId = req.userId;
  const { parentId = null } = req.query;

  if (parentId !== null && !isValidFileId(parentId)) {
    return res.status(400).json({ error: 'Invalid parent id' });
  }

  const result = filesService.getMoveFolders(
    userId,
    parentId ?? null
  );

  if (result === 'PARENT_NOT_FOUND') {
    return res.status(404).json({ error: 'Parent not found' });
  }

  if (result === 'INVALID_PARENT') {
    return res.status(400).json({ error: 'Invalid parent' });
  }

  if (result === 'NO_PERMISSION') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  return res.status(200).json(result);
};


// POST /api/files
const createFile = async (req, res) => {
  const userId = req.userId;
  const { name, type, parentId, content } = req.body || {};

  if (!name || !type) {
    return res.status(400).json({ error: 'Missing name or type' });
  }

  const result = await filesService.createFile(userId, name, type, parentId, content);
  
  if (result === 'PARENT_NOT_FOUND') {
    return res.status(404).json({ error: 'Parent not found' });
  }

  if (result === 'INVALID_PARENT') {
    return res.status(400).json({ error: 'Invalid parent' });
  }

  if (result === 'NO_PERMISSION') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  if (result === 'INVALID_TYPE') {
    return res.status(400).json({ error: 'Invalid type' });
  }

  if (result === 'CPP_ERROR') {
    return res.status(500).json({ error: 'File server unavailable' });
  }
  
  const file = result.file;

  try {
    permissionStore.createPermission(file.id, userId, 'ADMIN');
  } catch (err) {
    console.error('Warning: Failed to grant initial permission:', err);
  }

  return res.status(201).json(file);
};

// GET /api/files/:id
const getFileById = async (req, res) => {
  const userId = req.userId;
  const fileId = req.params.id;

  // Validate file id format
  if (!isValidFileId(fileId)) {
    return res.status(400).json({ error: "Invalid file id" });
  }

  let result;
  try {
    result = await filesService.getFileByIdWithContent(fileId, userId);
  } catch (err) {
    // Defensive: unexpected crash in service layer
    return res.status(500).json({ error: "Unexpected error" });
  }

  switch (result.status) {
    case "NOT_FOUND":
      return res.status(404).json({ error: "File not found" });

    case "FORBIDDEN":
      return res.status(403).json({ error: "Forbidden" });

    case "CPP_ERROR":
      return res.status(503).json({ error: "File server unavailable" });

    case "OK": {
      const file = result.file;

      // Explicit, non-heuristic classification
      if (file.type === "file" && file.contentType === "image") {
        return res.status(200).json({
          ...file,
          isImage: true,
        });
      }

      // All other cases: folder or text file
      return res.status(200).json({
        ...file,
        isImage: false,
      });
    }

    default:
      return res.status(500).json({ error: "Unexpected error" });
  }
};



// PATCH /api/files/:id
const updateFileById = async (req, res) => {
  const userId = req.userId;
  const fileId = req.params.id;
  const { name, content } = req.body || {};

  if (!isValidFileId(fileId)) {
    return res.status(400).json({ error: 'Invalid file id' });
  }

  if (name === undefined && content === undefined) {
    return res.status(400).json({ error: 'Nothing to update' });
  }

  if (name !== undefined) {
    const result = filesService.updateFileNameById(fileId, userId, name);

    if (result === 'NOT_FOUND') {
      return res.status(404).json({ error: 'File not found' });
    }

    if (result === 'NO_PERMISSION') {
      return res.status(403).json({ error: 'Forbidden' });
    }
  }

  if (content !== undefined) {
    const result = await filesService.updateFileContent(fileId, userId, content);

    if (result === 'NOT_FOUND') {
      return res.status(404).json({ error: 'File not found' });
    }

    if (result === 'NO_PERMISSION') {
      return res.status(403).json({ error: 'Forbidden' });
    }

    if (result === 'NOT_A_FILE') {
      return res.status(400).json({ error: 'Cannot update content of folder' });
    }

    if (result === 'CPP_ERROR') {
      return res.status(500).json({ error: 'File server unavailable' });
    }
  }

  return res.status(204).send();
};

// PUT /api/files/:id/replace
const replaceFileById = async (req, res) => {
  const userId = req.userId;
  const fileId = req.params.id;

  if (!isValidFileId(fileId)) {
    return res.status(400).json({ error: "Invalid file id" });
  }

  if (!req.file) {
    return res.status(400).json({ error: "Missing file" });
  }

  const buffer = req.file.buffer;

  const result = await filesService.replaceFileContent(
    fileId,
    userId,
    buffer,
  );

  switch (result) {
    case "NOT_FOUND":
      return res.status(404).json({ error: "File not found" });
    case "NO_PERMISSION":
      return res.status(403).json({ error: "Forbidden" });
    case "NOT_A_FILE":
      return res.status(400).json({ error: "Not a file" });
    case "CPP_ERROR":
      return res.status(500).json({ error: "File server unavailable" });
    case "OK":
      return res.status(204).send();
    default:
      return res.status(500).json({ error: "Internal server error" });
  }
};


// DELETE /api/files/:id
const deleteFileById = async (req, res) => {
  const userId = req.userId;
  const fileId = req.params.id;

  if (!isValidFileId(fileId)) {
    return res.status(400).json({ error: 'Invalid file id' });
  }

  const result = await filesService.deleteFileById(fileId, userId);

  if (result === 'NOT_FOUND') {
    return res.status(404).json({ error: 'File not found' });
  }

  if (result === 'FORBIDDEN') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  if (result === 'CPP_ERROR') {
    return res.status(500).json({ error: 'File server unavailable' });
  }

  return res.status(204).send();
};

// PATCH /api/files/:id/star
const toggleStar = (req, res) => {
  const userId = req.userId;
  const itemId = req.params.id;

  if (!isValidFileId(itemId)) {
    return res.status(400).json({ error: 'Invalid item id' });
  }

  const result = filesService.toggleFileStar(itemId, userId);
  if (result === 'NOT_FOUND') {
    return res.status(404).json({ error: 'item not found' });
  }

  if (result === 'NO_PERMISSION') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  if (result.status === 'OK') {
    // Let the client know the new star status
    return res.status(200).json({ id: itemId, starred: result.isStarred });
  }

  return res.status(500).json({ error: 'Internal server error' });
};

// GET /api/files/bin
const getBin = (req, res) => {
  const userId = req.userId;

  try {
    const items = filesService.getTrashForUser(userId);

    return res.status(200).json(attachOwnerInfo(items, userId));
  } catch (err) {
    console.error('Failed to fetch bin items:', err);
    return res.status(500).json({ error: 'Internal server error' });
  }
};

// PATCH /api/files/:id/bin
const moveToBin = (req, res) => {
  const userId = req.userId;
  const itemId = req.params.id;

  if (!isValidFileId(itemId)) {
    return res.status(400).json({ error: 'Invalid item id' });
  }

  const result = filesService.moveToBin(itemId, userId);

  if (result === 'NOT_FOUND') {
    return res.status(404).json({ error: 'Item not found' });
  }

  if (result === 'NO_PERMISSION') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  return res.status(204).send();
};

// PATCH /api/files/:id/restore
const restoreFromBin = (req, res) => {
  const userId = req.userId;
  const itemId = req.params.id;

  if (!isValidFileId(itemId)) {
    return res.status(400).json({ error: 'Invalid item id' });
  }

  const result = filesService.restoreFromBin(itemId, userId);

  if (result === 'NOT_FOUND') {
    return res.status(404).json({ error: 'Item not found' });
  }

  if (result === 'NO_PERMISSION') {
    return res.status(403).json({ error: 'Forbidden' });
  }

  return res.status(204).send();
};

// POST /api/files/:id/move
const moveFile = (req, res) => {
  const userId = req.userId;
  const fileId = req.params.id;
  const { targetParentId } = req.body || {};

  if (!isValidFileId(fileId)) {
    return res.status(400).json({ error: 'Invalid file id' });
  }

  if (targetParentId !== null && !isValidFileId(targetParentId)) {
    return res.status(400).json({ error: 'Invalid target parent id' });
  }

  const result = filesService.moveItem(userId, fileId, targetParentId ?? null);

  switch (result) {
    case 'NOT_FOUND':
    case 'TARGET_NOT_FOUND':
      return res.status(404).json({ error: 'Item not found' });

    case 'NO_PERMISSION':
      return res.status(403).json({ error: 'Forbidden' });

    case 'IN_BIN':
    case 'TARGET_IN_BIN':
      return res.status(400).json({ error: 'Cannot move items in bin' });

    case 'INVALID_TARGET':
      return res.status(400).json({ error: 'Invalid target folder' });

    case 'CYCLE':
      return res.status(400).json({ error: 'Cannot move folder into its descendant' });

    case 'OK':
      return res.status(204).send();

    default:
      return res.status(500).json({ error: 'Internal server error' });
  }
};


module.exports = {
  getFilesInRootForUser,
  getSharedWithMe,
  getFileById,
  createFile,
  updateFileById,
  replaceFileById,
  deleteFileById,
  toggleStar,
  getBin,
  moveToBin,
  restoreFromBin,
  getRecentFiles,
  getMoveFolders,
  moveFile
};
